### ISSUE TITLE
Incorrect namespace for ssn checkout field

### ISSUE THREAD

**Issue by olafurns7** [CoveAS/dropp-for-woocommerce#7]
Incorrect namespace is being used for the social security number field in the checkout.

Tried creating a branch and a pull request but it's protected :smile

File: classes/class-social-security-number.php - line: 89

Codefix:

```
	/**
	 * Checkout fields
	 *
	 * @param  array $fields Checkout fields.
	 * @return array         Checkout fields.
	 */
	public static function checkout_fields( $fields ) {
		// Get the shipping method.
		$shipping_method = Shipping_Method\Dropp::get_instance();

		// Add the new field.
		$fields['billing']['billing_dropp_ssn'] = [
			'type'        => 'textarea',
			'label'       => __( 'Social Security Number', 'dropp-for-woocommerce' ),
			'placeholder' => '0000000000',
			'required'    => $shipping_method->require_ssn,
			'priority'    => 100,
		];

		return $fields;
	}
	
```

**Comment by forsvunnet** [comment]
@olafurns7 thanks for reporting this. Fixed it now.
For creating pull requests on repo's that you do not have access to you'll have to first fork the repo and then you can create a pull request for the upstream branch.

**Comment by olafurns7** [comment]
Ah - not done much of these :)

Great, thanks for the quick response!
