### ISSUE TITLE
Calculations for free shipping

### ISSUE THREAD

**Issue by olafurns7** [CoveAS/dropp-for-woocommerce#8]
Hi,

I have a bit of an "issue" - I offer free shipping for orders over 15.000 ISK.

However I'm also working with a few customers who have outstanding discount codes ranging for 10-20% discount.

The Dropp plugin uses the **pre**-discount price to determine if the shipping is free or not, however I'm also using a shipping plugin from the icelandic post, and they use the price **after** discount to determine if it fits the criteria of being over 15.000 ISK.

Is there any chance of adding some sort of .. toggle for this in the plugin, so that the post-discount price is used to determine the free shipping criteria?

**Comment by olafurns7** [comment]
Example:

![image](https://user-images.githubusercontent.com/85343965/153069026-5e6c7507-54c5-4274-ab59-4c1c393421cb.png)

**Comment by olafurns7** [comment]
🚀

**Comment by olafurns7** [comment]
@forsvunnet actually.. this wasn't that easy fix! 😄 

` WC()->cart->get_cart_contents_total()`

Seems this function returns the value of the cart **before** tax, so it's still not calculating correctly: 

![image](https://user-images.githubusercontent.com/85343965/153435858-fa4c74b8-f748-4f99-8298-3d6480f88fd0.png)

However after putting my php/woocommerce hat on I've found the , I think correct solution:

```	
if ( (WC()->cart->get_cart_contents_total() + WC()->cart->get_cart_contents_tax()) < $threshold ) {
			// Cart is less than threshold. Shipping is not free.
			return $cost;
		}
```


This yields correct free shipping both with discount codes or without them.

I've done this for my site at the moment, but maybe you can re-fix it and update it in your next release 😄

**Comment by forsvunnet** [comment]
Thanks for the suggested fix. I'll have to make an adjustment in order to support the prices including/excluding tax setting in WooCommerce. I'll be sure to include this for the next release.
